#+AUTHOR: Wojciech 'vifon' Siewierski
#+TITLE: My GNU Emacs config

* Files and directories
** [[file:Makefile][Makefile]]
   Used to deploy this config (basically symlink it at =~/.emacs.d=)
   and create a few derived files (byte-compilation).

** [[file:utils/][utils/]]
   Helper scripts to debug and maintain Emacs.

** [[file:emacs.d/][emacs.d/]]
   The layout inside this directory is mostly described in
   [[file:emacs.d/init.el][emacs.d/init.el]] which loads all the other files.

*** [[file:emacs.d/lisp/][emacs.d/lisp/*]]
    This is where most of the actual config lives.

    It's all loaded by [[file:emacs.d/config-lib.el][config-lib.el]].

* Package management
  The external packages are fetched and installed with [[https://github.com/raxod502/straight.el][straight.el]],
  =package.el= is not being utilized.

* Disclaimer
  This is a private repo and it may be subject to the Git history
  rewrites and other unsightly changes.  Feel free to borrow parts of
  it but there is no warranty included whatsoever.
