(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(TeX-PDF-mode t)
 '(TeX-view-program-list (quote (("Evince" "evince %o") ("Zathura" "zathura %o"))))
 '(TeX-view-program-selection
   (quote
    (((output-dvi style-pstricks)
      "dvips and gv")
     (output-dvi "xdvi")
     (output-pdf "Evince")
     (output-html "xdg-open"))))
 '(bmkp-last-as-first-bookmark-file "~/.emacs.bmk")
 '(calendar-date-style (quote european))
 '(calendar-latitude 52.26)
 '(calendar-longitude 21.02)
 '(calendar-mark-diary-entries-flag nil)
 '(calendar-mark-holidays-flag nil)
 '(calendar-week-start-day 1)
 '(cc-search-directories
   (quote
    ("." "/usr/include" "/usr/local/include/*" "/home/vifon/local/include")))
 '(cperl-continued-statement-offset 0)
 '(cperl-indent-level 4)
 '(custom-safe-themes
   (quote
    ("cbef37d6304f12fb789f5d80c2b75ea01465e41073c30341dc84c6c0d1eb611d" "9dae95cdbed1505d45322ef8b5aa90ccb6cb59e0ff26fef0b8f411dfc416c552" "3b819bba57a676edf6e4881bd38c777f96d1aa3b3b5bc21d8266fa5b0d0f1ebf" "146d24de1bb61ddfa64062c29b5ff57065552a7c4019bee5d869e938782dfc2a" "60f04e478dedc16397353fb9f33f0d895ea3dab4f581307fbf0aa2f07e658a40" "73fe242ddbaf2b985689e6ec12e29fab2ecd59f765453ad0e93bc502e6e478d6" "9c26d896b2668f212f39f5b0206c5e3f0ac301611ced8a6f74afe4ee9c7e6311" "99cbc2aaa2b77374c2c06091494bd9d2ebfe6dc5f64c7ccdb36c083aff892f7d" "d677ef584c6dfc0697901a44b885cc18e206f05114c8a3b7fde674fce6180879" "8aebf25556399b58091e533e455dd50a6a9cba958cc4ebb0aab175863c25b9a4" default)))
 '(dired-dwim-target t)
 '(ediff-grab-mouse nil)
 '(ediff-window-setup-function (quote ediff-setup-windows-plain))
 '(flymake-gui-warnings-enabled t)
 '(focus-follows-mouse t)
 '(glasses-separate-parentheses-p nil)
 '(helm-external-programs-associations (quote (("pdf" . "evince"))))
 '(helm-swoop-speed-or-color t)
 '(httpd-port 38080)
 '(inhibit-startup-screen t)
 '(initial-buffer-choice nil)
 '(initial-scratch-message "")
 '(mouse-autoselect-window nil)
 '(rainbow-x-colors-major-mode-list
   (quote
    (emacs-lisp-mode lisp-interaction-mode c-mode c++-mode java-mode sh-mode)))
 '(recentf-exclude (quote ("^/media/" "COMMIT_EDITMSG$" "^mutt-")))
 '(safe-local-variable-values
   (quote
    ((eval ispell-change-dictionary "pl")
     (eval flyspell-buffer))))
 '(sentence-end-double-space nil)
 '(server-raise-frame nil)
 '(tramp-default-method "scp")
 '(viper-toggle-key [(control 96)])
 '(viper-want-ctl-h-help t)
 '(winner-mode t)
 '(woman-fill-column 80))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(diff-added ((((background dark)) (:foreground "green"))))
 '(diff-changed ((((background dark)) (:foreground "yellow"))))
 '(diff-context ((((background dark)) (:foreground "White")) (t (:foreground "Black"))))
 '(diff-file-header ((((background dark)) (:foreground "Cyan" :background "Black")) (t (:foreground "Red" :background "White"))))
 '(diff-header ((((background dark)) (:foreground "Cyan")) (t (:foreground "Red"))))
 '(diff-hl-change ((t (:background "yellow3" :foreground "yellow2"))))
 '(diff-hl-delete ((t (:background "firebrick" :foreground "red"))))
 '(diff-hl-insert ((t (:background "lime green" :foreground "green"))))
 '(diff-hunk-header ((((background dark)) (:foreground "Black" :background "#05057F7F8D8D")) (t (:foreground "White" :background "Salmon"))))
 '(diff-index ((((background dark)) (:foreground "Magenta")) (t (:foreground "Green"))))
 '(diff-indicator-added ((t (:inherit diff-added))))
 '(diff-indicator-changed ((t (:inherit diff-changed))))
 '(diff-indicator-removed ((t (:inherit diff-removed))))
 '(diff-nonexistent ((((background dark)) (:foreground "#FFFFFFFF7474")) (t (:foreground "DarkBlue"))))
 '(diff-refine-added ((t (:inherit diff-added :background "green4"))))
 '(diff-refine-removed ((t (:inherit diff-removed :background "red4"))))
 '(diff-removed ((((background dark)) (:foreground "red"))))
 '(dired-marked ((t (:inherit font-lock-warning-face :foreground "tomato"))))
 '(dired-warning ((t (:inherit font-lock-warning-face))))
 '(error ((t (:foreground "red" :underline (:color foreground-color :style wave) :weight bold))))
 '(font-lock-preprocessor-face ((t (:inherit font-lock-builtin-face))))
 '(font-lock-warning-face ((((class color) (min-colors 88) (background dark)) (:foreground "Red" :weight bold))))
 '(helm-swoop-target-line-block-face ((t nil)))
 '(helm-swoop-target-line-face ((t nil)))
 '(helm-swoop-target-word-face ((t (:background "yellow"))))
 '(highlight ((t (:background "#282828"))))
 '(hl-line ((t (:inherit highlight :background "grey20"))))
 '(indent-guide-face ((t (:foreground "#666666"))))
 '(italic ((t (:slant italic))))
 '(jabber-chat-prompt-local ((t (:foreground "#4444ff" :weight bold))) t)
 '(jabber-roster-user-online ((t (:foreground "#4444ff" :slant normal :weight bold))) t)
 '(minimap-semantic-function-face ((((background dark)) (:inherit (font-lock-function-name-face minimap-font-face) :background "gray10" :box (:line-width 1 :color "white") :height 3.0))))
 '(org-block-begin-line ((t (:inherit org-meta-line :background "#243A43"))) t)
 '(org-block-end-line ((t (:inherit org-meta-line :background "#243A43"))) t)
 '(table-cell ((t (:background "gray29" :foreground "gray90" :inverse-video nil))))
 '(term-color-blue ((t (:background "#4276b8" :foreground "#4276b8"))))
 '(term-color-cyan ((t (:background "#0b939b" :foreground "#0b939b"))))
 '(term-color-green ((t (:background "#00cc00" :foreground "#00cc00"))))
 '(term-color-magenta ((t (:background "#95709b" :foreground "#95709b"))))
 '(term-color-red ((t (:background "#dc0000" :foreground "#dc0000"))))
 '(term-color-yellow ((t (:background "#c4a000" :foreground "#c4a000"))))
 '(viper-minibuffer-emacs ((t nil)) t)
 '(viper-minibuffer-insert ((t nil)) t)
 '(viper-minibuffer-vi ((t nil)) t)
 '(warning ((t (:foreground "yellow" :underline (:color foreground-color :style wave) :weight bold))))
 '(woman-bold ((t (:inherit bold :foreground "red"))) t)
 '(woman-italic ((t (:inherit (italic bold) :foreground "green"))) t))

(put 'downcase-region 'disabled nil)
(put 'upcase-region 'disabled nil)
(put 'scroll-left 'disabled nil)
(put 'narrow-to-region 'disabled nil)
(put 'narrow-to-page 'disabled nil)
(put 'dired-find-alternate-file 'disabled nil)
(put 'erase-buffer 'disabled nil)
(put 'set-goal-column 'disabled nil)
